---
title: "Lab Updates October 18 2019"
author: "Andrew Allyn"
date: "10/18/2019"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Miguel
#### Who did you help this week?

* I helped Lindsay collect salmon scales in Bangor

#### Who helped you this week?

* Andy helped me with code for getting started on predicting fish abundance using neural networks

#### What did you achieve?

* I tried using self-organizing maps as a method for pattern recognition for the PN salmon scale growth data

#### What did you struggle with?

* I struggled with trying out different grid sizes and cluster numbers for the self-organizing maps

#### What would you like to work on next week?

* I would like to work on making plots for daily growth rates for the salmon phenology work, compare different grid sizes and cluster numbers in terms of interpretability, and develop alternative neural network configurations

#### Where do you need help from Kathy?

* After I run a series of alternative self-organizing maps and alternative cluster numbers, I need Kathy's help in deciding on which version is best

#### Where do you need help from other lab members?

* I think getting feedback on the self-organizing maps results from the salmon group would be helpful 

### Lindsay
#### Who did you help this week?

I found the code to wrap strip text in facets for Andrew. I also helped Zach with some ggplot code.

#### Who helped you this week?

Alex gave us a great presentation on the horrors that can arise from mixing Box and Git. 

#### What did you achieve?

*Salmon*

* Searched for Carlin-tagged salmon scales among DMR scale samples
* Organized, double-checked, put in order, and added necessary labelling to Carlin scales in preperation for handoff to Brandon
* Created a datasheet for Brandon that contains all necessary identifying information for each sample, but excluding individuals for which there was no scale collected
* Tried to figure out why DMR database does not include any Carlin-tagged scales collected before 1978... failed. 

*VTR*

* Continued with VTR vs trawl centroid analysis
* Mapped overlap, convergence of state centroids
* Conducted [pairwise comparisons of VTR vs trawl centroid trends](https://rpubs.com/lgcarlson/vtrcentroid)
* Conducted multiple comparisons of state level centroids by species

#### What did you struggle with?

I could not figure out why the 1977 scales I pulled are not in the DMR database, but they are in the Carlin datafile. Unfortunately, I don't think *anyone* knows the answer to this question.

#### What would you like to work on next week?

Next week I will deliver the scales to Brandon and Ruth while they're in town. I will continue working on the VTR data, and I will revisit the trawl data in light of Kathy's ideal to assess biomass accumulation by latitude. I look forward to a good discussion of mixed models at lab meeting. I also need to log my mileage from my trips to Orono. Maybe we can also re-instate Tidy Thursday.

### Andrew 
#### Who did you help this week?

I helped Zach with some more plotting and then some folks on the NSF Convergence team thinking about ROMS data output and how we end up using these types of data within the distribution models.

#### Who helped you this week?

This week I got help from Alex and the quant group during a productive meeting thinking through work flows, and especially, working with GitHub and Box. 

#### What did you achieve?

* COCA shelfwide assessment -- Found a bug early on in the week (box/GitHub issue, I think), got that fixed and ran things back through. Making plots now.
* JSDM (mostly NSF C Accel applicaiton) -- Prepped the Morley data, some data exploration, and ready to give the VAST model a shot next week. Talking to Cornell folks on Tuesday.

#### What did you struggle with?

* Data visualization. For the shelfwide assessment paper and COCA 
* Understanding the difference between fixed effects and random effects, and more specifically, random effects that themselves are surfaces (Gaussian Random Fields). (still don't get this -- but hoping lab meeting next week might help!)

#### What would you like to work on next week?

* Get Kathy shelfwide draft figures
* JSDM fitted for NSF C-Accel application
* Plan for how to fill in VAST knowledge gaps
* Seasonality/skill assessment brainstorm

#### Where do you need help from Kathy?

* I think all set -- a short week coming up for me as I head south Thursday for brother's wedding.   

#### Where do you need help from other lab members?

* Lab meeting: future lab meeting ideas. We've had two sessions of paper reading and curious to hear how people think those have been going, and what we'd like to do next?

### Matt
* Catch up on things I missed while on vacation
* Worked on river temperature projections for the shad project
  + Identified the longest temperature time series available for the Penobscot River
  + Downloaded the observered NLDAS air temp data and the projected LOCA air temp data
  + Modeled the Penobscot River temperature using the same methods as the CT river
* Continued working on the cross-habitat project
  + Meeting with Rob Dudley of the USGS next week to talk FW (invited by Lis)
* Performed lit review of use of water temperature from USGS river gages
  + Seems limited - most people use flow and air temp to derive water temperature
  + Flow and gage height are more complete time series
  + Ask Rob about river temperature accuracy and reliability
* Should have bottom temp data from ROMS model soonish
  + Continue with lobster catchability work






